server:
  host: localhost
  port: 8802
  tomcat:
    max-connections: 10000
    uri-encoding: UTF-8
swagger:
  enabled: true
project:
  token: /fmServer/oauth/token
  ver-code: /fmServer/sysUserInfo
spring:
  datasource:
    url: jdbc:mysql://47.107.67.202:3306/fm_test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: zhangtw
    password: tX33EPHG
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    cache-prefix: fm
    session:
      timeout: 2592000 ## 30*24*60*60
    password: rjsyb4138
#================= Spring Security start ===============
#================= Spring Security end =================
logging:
  level:
    org.fm: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
