server:
  host: localhost
  port: 8800
  tomcat:
    max-connections: 10000
    uri-encoding: UTF-8
swagger:
  enabled: true
project:
  token: /oauth/token
  ver-code: /sysUserInfo
spring:
  datasource:
    url: jdbc:mysql://129.211.14.58:3306/fm?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: Jinbang666...
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 28800
  redis:
    database: 0
    host: 129.211.14.58
    port: 6379
    cache-prefix: fm
    session:
      timeout: 2592000 ## 30*24*60*60
    password: 123456
#================= Spring Security start ===============
#================= Spring Security end =================
logging:
  level:
    com.autozi.app: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
